# GitHub Pages 配置文件
title: "123caiji - 学术个人主页"
description: "123caiji的个人学术主页，展示研究领域、发表论文和学术成果"
author: "123caiji"
email: "123caiji@example.com"
url: "https://123caiji.github.io"
baseurl: ""

# 社交媒体链接
social:
  github: "123caiji"
  email: "123caiji@example.com"
  website: "https://123caiji.github.io"

# 构建设置
markdown: kramdown
highlighter: rouge
theme: minima

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - .gitignore
  - .git
  - LICENSE

# 包含文件
include:
  - _pages

# 默认设置
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "123caiji"

